#      ___       __           __    __       __    _          
#     / _ | ____/ /____ ___ _/ /__ / /  ___ / /__ (_)_ ____ __
#    / __ |/ __/ __(_-</ _ `/  '_// _ \(_-</  '_// / // / // /
#   /_/ |_/_/  \__/___/\_,_/_/\_\/_//_/___/_/\_\/_/\_, /\_, / 
#                                                 /___//___/ 
#
# Версия конфига - НЕ МЕНЯЙТЕ!
config-version: 1.3

# Настройки...
# Интервал 180 секунд = 3 минуты
settings:
  interval: 180
  countdown:
    "60": 
      message: "§7[§fОчистка§7] §fОчистка сервера через §c1 §fминуту..."
      type: "message"
    "30":
      message: "§7[§fОчистка§7] §fОчистка сервера через §c30 §fсекунд..."
      type: "message"
    "20":
      message: "§7[§fОчистка§7] §fОчистка сервера через §c20 §fсекунд..."
      type: "message"
    "10":
      message: "§7[§fОчистка§7] §fОчистка сервера через §c10 §fсекунд..."
      type: "message"
    "5":
      message: "§7[§fОчистка§7] §fОчистка сервера через §c5 §fсекунд..."
      type: "message"
    "4":
      message: "§7[§fОчистка§7] §fОчистка сервера через §c4 §fсекунды..."
      type: "message"
    "3":
      message: "§7[§fОчистка§7] §fОчистка сервера через §c3 §fсекунды..."
      type: "message"
    "2":
      message: "§7[§fОчистка§7] §fОчистка сервера через §c2 §fсекунды..."
      type: "message"
    "1":
      message: "§7[§fОчистка§7] §fОчистка сервера через §c1 §fсекунду..."
      type: "message"
  completed:
    message: "§7[§fОчистка§7] §fОчистка сервера §aзавершена§f!"
    type: "message"
  
  toast-title: "Очистка"


# Опции очистки...
clear-options:
  clear-mobs: true 
  clear-items: true 

  mob-exceptions: 
    - "minecraft:horse"
    - "minecraft:iron_golem"
  item-exceptions: 
    - "minecraft:diamond"
    - "minecraft:nether_star"

# Сообщения...
messages:
  no_permission: "§cУ вас недостаточно прав."
  
